# Generated by Django 5.1.2 on 2024-10-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='emailAddress',
        ),
    ]
