# Generated by Django 5.1.2 on 2024-10-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideosName', models.CharField(max_length=100, verbose_name='Videos Name')),
                ('UploadFile', models.FileField(max_length=500, null=True, upload_to='Videos', verbose_name='Upload File')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('ModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('LevelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.schoollevels', verbose_name='Level Name')),
                ('SubjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subjects', verbose_name='Subject Name')),
            ],
        ),
    ]
