# Generated by Django 5.1.2 on 2024-11-04 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.questions', verbose_name='Question'),
        ),
    ]
