# Generated by Django 5.1.2 on 2024-11-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_assigntoclasses_teacher_askquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntoclasses',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teachers', verbose_name='Teacher Name'),
        ),
    ]
