# Generated by Django 5.1.2 on 2024-11-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_assigntoclasses_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='questionAsk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='base.askquestion'),
        ),
    ]
