# Generated by Django 5.1.2 on 2024-11-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerquestion',
            old_name='questionAsk',
            new_name='question_ask',
        ),
    ]
