# Generated by Django 5.1.2 on 2024-11-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_questionask_answerquestion_question_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='askquestion',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='base.subjects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='askquestion',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
