# Generated by Django 5.1.2 on 2024-11-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_askquestion_subject_alter_askquestion_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='askquestion',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to='base.schoolclases'),
            preserve_default=False,
        ),
    ]
