# Generated by Django 5.1.2 on 2024-11-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notification_ask_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='answer_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='base.answerquestion'),
        ),
    ]
