# Generated by Django 5.1.4 on 2024-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_comments_options_comments_isapproved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageTitle', models.CharField(max_length=100, verbose_name='Image Title')),
                ('Image', models.ImageField(upload_to='web-images', verbose_name='Upload Image')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('ModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name': 'Web Image',
                'verbose_name_plural': 'Web Images',
            },
        ),
    ]
