# Generated by Django 5.1.4 on 2024-12-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_askquestion_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question_ask',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.askquestion'),
        ),
    ]
