# Generated by Django 5.1.4 on 2024-12-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_answerquestion_question_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='askquestion',
            name='LevelName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.schoollevels', verbose_name='Level Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='question_ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.askquestion'),
        ),
    ]
